### PR TITLE
CHAR String Function: #13

### PR DESCRIPTION
**Pull request by Lilit0x**
CHAR String function

### CODE REVIEW

**Comment by Lilit0x** [comment]
I'll squash the commits in about 2 minutes now.
Thanks

**Comment by AmrDeveloper** [comment]
I suggest to only create branches from master to avoid conflicts for example.

After finishing PR, update your fork and then update the local master, then create a new branch for the next PR

**Comment by Lilit0x** [comment]
> I suggest to only create branches from master to avoid conflicts for example.
> 
> After finishing PR, update your fork and then update the local master, then create a new branch for the next PR

Yeahh, I forgot to do that for this PR. My bad, the next one will be okay.
Do you want to resolve the conflicts or should I?

**Comment by AmrDeveloper** [comment]
Related to `text_char` we need to check if it valid or returning default value

```rs
let code = inputs[0].as_number() as u32;
if let Some(character) = char::from_u32(code) {
    return Value::Text(character.to_string());
}
return Value::Text("".to_string());
```

In the current state we just check argument type so we need to return default value of function has problem

**Comment by Lilit0x** [comment]
Okay, got it

**Comment by AmrDeveloper** [comment]
> > I suggest to only create branches from master to avoid conflicts for example.
> > After finishing PR, update your fork and then update the local master, then create a new branch for the next PR
> 
> Yeahh, I forgot to do that for this PR. My bad, the next one will be okay. Do you want to resolve the conflicts or should I?

You should resolve it on local machine or using github UI check that lines that has <<< or >>> and do manual merging, if you need any help just write here

**Pull request closed without merging**
