### PR TITLE
feat: Migrate from `git2` to `gix`

### PR DESCRIPTION
**Pull request by AmrDeveloper**
Migrate from `git2` to `gix`

### CODE REVIEW

**Comment by AmrDeveloper** [comment]
@Byron Migration and Handling Remote and Local branches,

Feel free to code review and feedback

**Review by Byron — COMMENTED** [review]
Thanks for the heads-up, this was fast!

I have a few general comments only, and the usage of `gix` seems alright even though we will probably never know without tests.

**Comment by AmrDeveloper** [comment]
I have updated passing &[T] and workspace, but i am working now on new Diagnostic object to be dynamic and support warn, help ...etc so we can keep string for now and migrate directly to the new Diagnostic

Thank you

**Comment by AmrDeveloper** [comment]
If everything else is good once you approve review we can merge @Byron

**Comment by Byron** [comment]
All looks as good as it can in relation to the usage of `gitoxide`, thanks a lot for making it happen. Please, do go ahead with the merge.

**Comment by AmrDeveloper** [comment]
Merged, Thank you @Byron

**Pull request merged**
