### PR TITLE
implement 'describe table_name' to show fields and types of a table

### PR DESCRIPTION
**Pull request by jossephus**
Implement mysql like 'describe table_name' to show what the available fields and their types are in a given table. Example shown in the picture below.
image

It shows this error if the requested table does not exist
image

### CODE REVIEW

**Comment by AmrDeveloper** [comment]
Hello @jossephus,

Thanks for implementing this cool feature, Once the first PR is merged we need to fix clippy comments and resolve conflikt

Thank you,

**Comment by AmrDeveloper** [comment]
@jossephus There are some conflicts we need to solve them because the last PR :D

**Comment by jossephus** [comment]
I have resolved them. Thanks again.

**Comment by AmrDeveloper** [comment]
Thank you

**Pull request merged**
